// File generated by the FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Provides Firebase options for initializing Firebase in the app.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.windows)) {
      return windows;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.linux)) {
      return linux;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgDWxmEPQl_azglznutMUKoA2HVN2xPuo',
    appId: '1:284434143597:android:fc8c62a4479c0f4a7da264',
    messagingSenderId: '284434143597',
    projectId: 'letsholo-money',
    storageBucket: 'letsholo-money.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgDWxmEPQl_azglznutMUKoA2HVN2xPuo',
    appId: '1:284434143597:ios:87ab1e1c68486b6e7da264',
    messagingSenderId: '284434143597',
    projectId: 'letsholo-money',
    storageBucket: 'letsholo-money.appspot.com',
    iosBundleId: 'com.letsholo.money',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgDWxmEPQl_azglznutMUKoA2HVN2xPuo',
    appId: '1:284434143597:windows:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '284434143597',
    projectId: 'letsholo-money',
    authDomain: 'letsholo-money.firebaseapp.com',
    storageBucket: 'letsholo-money.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDgDWxmEPQl_azglznutMUKoA2HVN2xPuo',
    appId: '1:284434143597:linux:xxxxxxxxxxxxxxxxxxxxxxxx',
    messagingSenderId: '284434143597',
    projectId: 'letsholo-money',
    authDomain: 'letsholo-money.firebaseapp.com',
    storageBucket: 'letsholo-money.appspot.com',
  );
}
